INSERT INTO [dbo].[STUDENTINFO]([ROLLNO],
[STUDENTNAME],[CITY], [STATE],
[CONTACTNO],[ADMISSIONDATE])
VALUES (107,'PAVAN','BIJAPUR','KARNATAKA','9845778411','2021-09-12')

SELECT DISTINCT STATE FROM [dbo].[STUDENTINFO]